# NumPy library

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [2]:
import numpy as np

In [2]:
#np.array creates an array
a=np.array([1,2,3])
print (a)
#a.ndim returns the dimension of the array
a.ndim

[1 2 3]


1

In [4]:
b=np.array([[1.1,2.4,3.3],[4.1,5.2,6.5]])
print (b)
print(b.ndim)
#b.shape returns the shape(number of rows, number of columns)
print(b.shape)
#b.dtype returns the data type of the elements
print(b.dtype)

[[1.1 2.4 3.3]
 [4.1 5.2 6.5]]
2
(2, 3)
float64


In [5]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],"\n")
print(c,"\n")
#print 7 ?
print(c[1,2],"\n")
print("Second row",c[-2,:],"\n")# : = all elements 
print("Last column",c[:,-1],"\n")
print("The middle 2 elements in row 2",c[1,1:3],"\n")
#set 3 = 20
c[0,2]=20
print("After change","\n",c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

7 

Second row [5 6 7 8] 

Last column [ 4  8 12] 

The middle 2 elements in row 2 [6 7] 

After change 
 [[ 1  2 20  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
#np.zeros(rows,columns) -> creates array filled with zeros
a=np.zeros((2,3))
print (a,"\n")
#np.ones(rows,columns) -> creates array filled with ones
b=np.ones((2,3))
print (b,"\n")
#np.full((rows,columns),number) -> creates array filled with specific number
c=np.full((2,3),4)
print (c,"\n")
#np.identity(square -> Rows = columns) -> creates array filled with ones at the diagonal
s=np.identity(3)
print(s,'\n','\n',s)

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[4 4 4]
 [4 4 4]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#np.random.rand creates array of random numbers between 0 and 1 of specific size
d=np.random.rand(2,3)
print(d,"\n")
#np.random.randint creates array of random numbers between specified start and end integer numbers of specific size
e=np.random.randint(1,6,size=(2,3))#end is not included
print(e)

[[0.11026789 0.92358708 0.94745296]
 [0.86271986 0.38255778 0.75556645]] 

[[2 5 2]
 [3 3 4]]


In [8]:
x1=np.array([[1,2,3],[4,5,6]])
print(x1,"\n")
#Any change in x2 will be applied on x1
x2=x1
x2[0,1]=10
print("x1","\n",x1,"\n\n","x2","\n",x2)

[[1 2 3]
 [4 5 6]] 

x1 
 [[ 1 10  3]
 [ 4  5  6]] 

 x2 
 [[ 1 10  3]
 [ 4  5  6]]


In [9]:
y1=np.array([[1,2,3],[4,5,6]])
print(y1,"\n")
#copy() creates copy of y1 so any change in y2 will not be applied on y1
y2=y1.copy()
y2[0,1]=10
print("y1","\n",y1,"\n\n","y2","\n",y2)

[[1 2 3]
 [4 5 6]] 

y1 
 [[1 2 3]
 [4 5 6]] 

 y2 
 [[ 1 10  3]
 [ 4  5  6]]


In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("arr","\n",arr,"\n")
print("arr+2","\n",arr+2,"\n")
print("arr-2","\n",arr-2,"\n")
print("arr*2","\n",arr*2,"\n")
print("arr/2","\n",arr/2,"\n")
print("arr**2","\n",arr**2,"\n")

arr 
 [[1 2 3 4]
 [5 6 7 8]] 

arr+2 
 [[ 3  4  5  6]
 [ 7  8  9 10]] 

arr-2 
 [[-1  0  1  2]
 [ 3  4  5  6]] 

arr*2 
 [[ 2  4  6  8]
 [10 12 14 16]] 

arr/2 
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]] 

arr**2 
 [[ 1  4  9 16]
 [25 36 49 64]] 



In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
#repeat(arr,number) flattening the array and repeat the array number of times
print(arr,"\n")

arr1= np.repeat(arr,2) 
print(arr1,"\n")

#if the axis is specified no flattening will happen
arr2 = np.repeat(arr,2,axis=0)# 0=row
print(arr2,"\n")

arr2 = np.repeat(arr,2,axis=1)# 1=column
print(arr2,"\n")

[[1 2 3 4]
 [5 6 7 8]] 

[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8] 

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]] 

[[1 1 2 2 3 3 4 4]
 [5 5 6 6 7 7 8 8]] 



In [12]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
#np.vstack creates vertical stack of specific order ([order])
print("vertical","\n",np.vstack([a,b,a,b]),"\n")
#np.hstack creates horizontal stack of specific order ([order])
print("horizontal",np.hstack([b,a,b,a]))

vertical 
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]] 

horizontal [5 6 7 8 1 2 3 4 5 6 7 8 1 2 3 4]


In [13]:
k=np.array([[1,2,3,4],[5,6,7,8]])
k1=np.array([[9,10,11,12],[13,14,15,16]])
print(np.concatenate((k,k1),axis=0),"\n")
print(np.concatenate((k,k1),axis=1),"\n")
print(np.vstack([k,k1]),"\n")
print(np.hstack([k,k1]),"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]] 



In [3]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
# 11,12,16,17
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [16]:
# diagonal
a[(0,1,2,3,4),(0,1,2,3,4)]

array([ 1,  7, 13, 19, 25])

In [17]:
#np.arange(start,end,number of steps) creates array , end is not included
x=np.arange(1,10,2)
print(x,"\n")
#np.linspace(start,end,number of samples) creates evenly spaced samples 
y=np.linspace(1,100,10)
print(y,"\n")
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#arr.reshape(Rows,columns) changes the array size (before 7*2=14, after must equal 14)
arr1=arr.reshape(7,2)
print(arr1,"\n")
print(arr1.flat[:],"\n")#flattening the array
#np.transpose(arr1)-> row=column and column=row
print(np.transpose(arr1),"\n")

[1 3 5 7 9] 

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 12 14]] 



In [18]:
u=np.array([[1,2,3,4],[5,6,7,8]])
u1=np.append(u,[[9,10,11,12]],axis=0)
u2=np.append(u,[[5],[9]],axis=1)
print(u,"\n\n",u1,"\n\n",u2)

[[1 2 3 4]
 [5 6 7 8]] 

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[1 2 3 4 5]
 [5 6 7 8 9]]


In [19]:
r=k=np.array([[1,2,3,4],[5,6,7,8]])
r1=np.insert(r,0,[[11,12,13,14]],axis=0)
r2=np.insert(r,4,[10,11],axis=1)
print(r,"\n\n",r1,"\n\n",r2,"\n\n")
r3=np.delete(r,1,axis=1)
print(r3)

[[1 2 3 4]
 [5 6 7 8]] 

 [[11 12 13 14]
 [ 1  2  3  4]
 [ 5  6  7  8]] 

 [[ 1  2  3  4 10]
 [ 5  6  7  8 11]] 


[[1 3 4]
 [5 7 8]]


# Pandas library

In [ ]:
import pandas as pd

## Series

In [ ]:
#Series like list but with the presence of the index
s=pd.Series([1,2,3,4,'Ahmed',np.nan,9])
print(s)

0        1
1        2
2        3
3        4
4    Ahmed
5      NaN
6        9
dtype: object


In [ ]:
#Series like list but with the presence of the index
s=pd.Series([1,2,3,4,'Ahmed',np.nan,9])
print(s)
print(s,"\n")
data=np.array(['a','b','c','d'])
s1=pd.Series(data)
print(s1,"\n")
#Series from dictionary
data1={'a':1,'b':5,'c':8,'d':10}
s2=pd.Series(data1)
print(s2,"\n")

0        1
1        2
2        3
3        4
4    Ahmed
5      NaN
6        9
dtype: object
0        1
1        2
2        3
3        4
4    Ahmed
5      NaN
6        9
dtype: object 

0    a
1    b
2    c
3    d
dtype: object 

a     1
b     5
c     8
d    10
dtype: int64 



## Data Frame

In [ ]:
#DataFrame is table with rows(index) and columns(columns)
df=pd.DataFrame(np.random.randint(1,7,size=(4,6)),index=['x','y','z','l'],columns=['a','b','c','d','e','f'])
print(df)

   a  b  c  d  e  f
x  5  5  6  5  6  5
y  4  3  1  4  6  5
z  3  2  5  3  3  1
l  5  4  6  1  3  1


In [ ]:
df.head(2)

a  b  c  d  e  f
x  5  5  6  5  6  5
y  4  3  1  4  6  5

In [ ]:
#describe() method is used for calculating some statistics of the data in the DataFrame
df.describe()

a         b         c         d         e         f
count  4.000000  4.000000  4.000000  4.000000  4.000000  4.000000
mean   4.250000  3.500000  4.500000  3.250000  4.500000  3.000000
std    0.957427  1.290994  2.380476  1.707825  1.732051  2.309401
min    3.000000  2.000000  1.000000  1.000000  3.000000  1.000000
25%    3.750000  2.750000  4.000000  2.500000  3.000000  1.000000
50%    4.500000  3.500000  5.500000  3.500000  4.500000  3.000000
75%    5.000000  4.250000  6.000000  4.250000  6.000000  5.000000
max    5.000000  5.000000  6.000000  5.000000  6.000000  5.000000

In [ ]:
#Other syntax to create the DataFrame
df1=pd.DataFrame({'A':0.1,
                 'B':pd.Series([1,2,3,4]),
                 'C':np.array([3]*4),
                 'D':['A','B','C','D'],
                 'E':'Good'})
print(df1,"\n")
#df1.head(rows) print the first nth rows
print(df1.head(2),"\n")
#df1.tail(rows) print the last nth rows
print(df1.tail(2),"\n")
#df1.index print the indexes names in the dataFrame
print(df1.index,"\n")
#df1.columns print the columns names in the dataFrame
print(df1.columns,"\n")
#df1.values print the values of the dataFrame
print(df1.values,"\n")

     A  B  C  D     E
0  0.1  1  3  A  Good
1  0.1  2  3  B  Good
2  0.1  3  3  C  Good
3  0.1  4  3  D  Good 

     A  B  C  D     E
0  0.1  1  3  A  Good
1  0.1  2  3  B  Good 

     A  B  C  D     E
2  0.1  3  3  C  Good
3  0.1  4  3  D  Good 

RangeIndex(start=0, stop=4, step=1) 

Index(['A', 'B', 'C', 'D', 'E'], dtype='object') 

[[0.1 1 3 'A' 'Good']
 [0.1 2 3 'B' 'Good']
 [0.1 3 3 'C' 'Good']
 [0.1 4 3 'D' 'Good']] 



In [ ]:
df2=pd.DataFrame(np.random.randint(1,6,size=(4,4)),index=['A','B','C','D'],columns=['one','two','three','four'])
df2

one  two  three  four
A    1    4      5     3
B    4    2      2     3
C    5    3      3     5
D    2    1      4     2

In [ ]:
df3=pd.DataFrame(np.random.randint(1,99,size=(3,3)),index=['A','B','C'],columns=['a','b','zzz'])
df3

a   b  zzz
A  31   8   75
B  18  97   22
C  87  38   58

In [ ]:
#df2.loc access the DataFrame based on the index or column name
print(df2.loc["B","three"],"\n")
print(df2.loc["C",:],"\n")
print(df2.loc[["C","D"],:],"\n")

2 

one      5
two      3
three    3
four     5
Name: C, dtype: int64 

   one  two  three  four
C    5    3      3     5
D    2    1      4     2 



In [ ]:
#df2.iloc access the DataFrame based on the element index
print(df2.iloc[1,2],"\n")
print(df2.iloc[-2,],"\n")
print(df2.iloc[2:4,],"\n")

2 

one      5
two      3
three    3
four     5
Name: C, dtype: int64 

   one  two  three  four
C    5    3      3     5
D    2    1      4     2 



In [ ]:
print(df2,"\n")
#df2.drop delete index or column with their values
a=df2.drop("three",axis=1)
print(a,"\n")
b=df2.drop("C",axis=0)
print(b,"\n")
c=df2.drop(["C","D"],axis=0)
print(c,"\n")

   one  two  three  four
A    1    4      5     3
B    4    2      2     3
C    5    3      3     5
D    2    1      4     2 

   one  two  four
A    1    4     3
B    4    2     3
C    5    3     5
D    2    1     2 

   one  two  three  four
A    1    4      5     3
B    4    2      2     3
D    2    1      4     2 

   one  two  three  four
A    1    4      5     3
B    4    2      2     3 



In [ ]:
#df2.reindex rearranges the indexes or the columns according to specified order
# if there index or column is not exist it will be created with not a number(NaN) values
print(df2,"\n")
x=df2.reindex(["B","A","C","D","E"])
print("x =","\n",x,"\n","\n")
y=df2.reindex(["two","four","one","three","five"],axis=1)
print("y =","\n",y,"\n")
# sort_index() order the indexes
print("x after sorting","\n",x.sort_index())

   one  two  three  four
A    1    4      5     3
B    4    2      2     3
C    5    3      3     5
D    2    1      4     2 

x = 
    one  two  three  four
B  4.0  2.0    2.0   3.0
A  1.0  4.0    5.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  NaN  NaN    NaN   NaN 
 

y = 
    two  four  one  three  five
A    4     3    1      5   NaN
B    2     3    4      2   NaN
C    3     5    5      3   NaN
D    1     2    2      4   NaN 

x after sorting 
    one  two  three  four
A  1.0  4.0    5.0   3.0
B  4.0  2.0    2.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  NaN  NaN    NaN   NaN


In [ ]:
x

one  two  three  four
B  4.0  2.0    2.0   3.0
A  1.0  4.0    5.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  NaN  NaN    NaN   NaN

In [ ]:
x.sort_index()

one  two  three  four
A  1.0  4.0    5.0   3.0
B  4.0  2.0    2.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  NaN  NaN    NaN   NaN

In [ ]:
print(y)
#y.isna() returns true if there value = NaN
print(y.isna())
#y.dropna() drop all values = Nan
print(y.dropna(axis=1))

   two  four  one  three  five
A    4     3    1      5   NaN
B    2     3    4      2   NaN
C    3     5    5      3   NaN
D    1     2    2      4   NaN
     two   four    one  three  five
A  False  False  False  False  True
B  False  False  False  False  True
C  False  False  False  False  True
D  False  False  False  False  True
   two  four  one  three
A    4     3    1      5
B    2     3    4      2
C    3     5    5      3
D    1     2    2      4


In [ ]:
x1=x.sort_index()
print(x1)
#x.max() print the maximum value default (0) in each columns
print(x1.max(axis=1))# Row = 1
#y.fillna() fill all values =Nan with the maximum
x.fillna(x1.max(),axis=0)

   one  two  three  four
A  1.0  4.0    5.0   3.0
B  4.0  2.0    2.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  NaN  NaN    NaN   NaN
A    5.0
B    4.0
C    5.0
D    4.0
E    NaN
dtype: float64


one  two  three  four
B  4.0  2.0    2.0   3.0
A  1.0  4.0    5.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  5.0  4.0    5.0   5.0

In [ ]:
x

one  two  three  four
B  4.0  2.0    2.0   3.0
A  1.0  4.0    5.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  NaN  NaN    NaN   NaN

In [ ]:
x.fillna(x1.max(),axis=0)

one  two  three  four
B  4.0  2.0    2.0   3.0
A  1.0  4.0    5.0   3.0
C  5.0  3.0    3.0   5.0
D  2.0  1.0    4.0   2.0
E  5.0  4.0    5.0   5.0